[[profile]]
name = "atdesk"

  [[profile.output]]
  match = "DP-1"
  enable = true
  mode = { width=1920, height=1080, refresh=144 }
  position = { x=0, y=0 }
  scale = 1.0

  [[profile.output]]
  match = "eDP-1"
  enable = false

[[profile]]
name = "default"

  [[profile.output]]
  match = "eDP-1"
  enable = true
  mode = { width=1920, height=1080, refresh=60 }
  position = { x=0, y=0 }
  scale = 1.5
