#!/usr/bin/env python3

import subprocess

class colors:
    reset='\033[0m'
    bold='\033[01m'
    disable='\033[02m'
    underline='\033[04m'
    reverse='\033[07m'
    strikethrough='\033[09m'
    invisible='\033[08m'
    class fg:
        black='\033[30m'
        red='\033[31m'
        green='\033[32m'
        orange='\033[33m'
        blue='\033[34m'
        purple='\033[35m'
        cyan='\033[36m'
        lightgrey='\033[37m'
        darkgrey='\033[90m'
        lightred='\033[91m'
        lightgreen='\033[92m'
        yellow='\033[93m'
        lightblue='\033[94m'
        pink='\033[95m'
        lightcyan='\033[96m'
    class bg:
        black='\033[40m'
        red='\033[41m'
        green='\033[42m'
        orange='\033[43m'
        blue='\033[44m'
        purple='\033[45m'
        cyan='\033[46m'
        lightgrey='\033[47m'

logo = """        .~7??JJJJ??7~.        
         :!JJJJJJJJ!:         
           :7JJJJ7:           
            .7JJ7.            
             :??:             
              77              
              77              
             ~JJ~             
:^:..    ..^7JJJJ7^..    ..:^:
.~7!!7777?JJJJJJJJJJ?7777!!!~.
 .7!.~~!~!!!!!!!!!!!!~!~~.!7. 
  .. . . :....::....: . . ..  
       .^..        ..^.       
       .:^~~~~~~~~~~^:.       """

logo_small = """    :7JJJ7:    
     .!J!.     
      .7.      
      .7.      
:~^^^!?J?!^^^~:
.^:^^^^^^^^^:^.
    :::::::    """

username = subprocess.getstatusoutput("whoami")[1]
hostname = subprocess.getstatusoutput("hostname")[1]
host = username + "@" + hostname
os = subprocess.getstatusoutput("cat /etc/os-release | grep 'PRETTY_NAME' | sed 's/PRETTY_NAME=//'")[1]
kernel = subprocess.getstatusoutput("uname -r")[1]
shell = subprocess.getstatusoutput("echo $SHELL | sed 's#.*/##'")[1]
wm = subprocess.getstatusoutput("echo $XDG_CURRENT_DESKTOP")[1]
term = subprocess.getstatusoutput('ps -o comm= -p "$(($(ps -o ppid= -p "$(($(ps -o sid= -p "$$")))")))"')[1]

print(f"""
{colors.fg.pink}    :7JJJ7:      {colors.reset}
{colors.fg.pink}     .!J!.       {colors.reset} {username + colors.fg.blue + "@" + colors.reset + hostname}
{colors.fg.pink}      .7.        {colors.reset}  {colors.fg.pink}os {colors.reset}{os.lower()}
{colors.fg.blue}      .7.        {colors.reset}   {colors.fg.blue}term {colors.reset}{shell.lower()}
{colors.fg.blue}:~^^^!?J?!^^^~:  {colors.reset}  {colors.fg.pink}wm {colors.reset}{wm.lower()}
{colors.fg.blue}.^:^^^^^^^^^:^.  {colors.reset} {colors.fg.blue}term {colors.reset}{term.lower()}
{colors.fg.blue}    :::::::    
{colors.reset}""")
